# # https://github.com/pypa/packaging.python.org/tree/main/source/guides/github-actions-ci-cd-sample

# name: Publish Python üêç distribution üì¶ to PyPI and TestPyPI

# on: push
#   # push: 
#   #   tags:
#   #     - v**

# jobs:
#   build:
#     name: Build distribution üì¶
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: "3.12"
#     - name: Install pypa/build
#       run: >-
#         python3 -m pip install build --user
#     - name: Build a binary wheel and a source tarball
#       run: python3 -m build
#     - name: Store the distribution packages
#       uses: actions/upload-artifact@v4
#       with:
#         name: python-package-distributions
#         path: dist/


#   publish-to-pypi:
#     name: Publish Python üêç distribution üì¶ to PyPI
#     needs:
#     - build
#     runs-on: ubuntu-latest
#     environment:
#       name: pypi
#       url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name
#     permissions:
#       id-token: write  # IMPORTANT: mandatory for trusted publishing
#     steps:
#     - name: Download all the dists
#       uses: actions/download-artifact@v4
#       with:
#         name: python-package-distributions
#         path: dist/
#     - name: Publish distribution üì¶ to PyPI
#       uses: pypa/gh-action-pypi-publish@release/v1